export const slides = [
  {
    mounth: "Сентябрь",
    year: "2018",
    photo: "/dates/slide-1.jpg",
    title: "ЕГЭ",
    description:
      "Я выбираю информатику в качестве дополнительного предмета и твердо решаю сдать её на 90+ баллов",
    dkTranslateX: 174.452,
    tbTranslateX: 79,
    mbTranslateX: 10.9434,
  },
  {
    mounth: "Август",
    year: "2019",
    photo: "/dates/slide-2.jpg",
    title: "Поступление",
    description:
      "Я отлично сдал ЕГЭ, суммарно вышло 268 баллов. Поступаю на бюджет в КНИТУ-КАИ по напралению Информационные Системы и Технологии",
    dkTranslateX: 19,
    tbTranslateX: -18.7864,
    mbTranslateX: -87.4037,
  },
  {
    mounth: "Октябрь",
    year: "2021",
    photo: "/dates/slide-3.jpg",
    title: "Выбор направления разработки",
    description: "Я твердо решаю для себя заниматься frontend разработкой",
    dkTranslateX: -109.95,
    tbTranslateX: -116.554,
    mbTranslateX: -162.209,
  },
  {
    mounth: "Декабрь",
    year: "2021",
    photo: "/dates/slide-4.webp",
    title: "Первые шаги",
    description:
      "Я показываю свой первый сайт на html+css своему преподавателю и получаю за это автоматом 5",
    dkTranslateX: -279.677,
    tbTranslateX: -226.711,
    mbTranslateX: -253.913,
  },
  {
    mounth: "Январь",
    year: "2022",
    photo: "/dates/slide-5.webp",
    title: "Серьезное решение",
    description:
      "Я начинаю выделять на свое обучение frontend разработке больше 3 часов в день и покупаю курсы Ивана Петриченко",
    dkTranslateX: -445.109,
    tbTranslateX: -335.62,
    mbTranslateX: -338.897,
  },
  {
    mounth: "Сентябрь",
    year: "2022",
    photo: "/dates/slide-6.jpg",
    title: "Вперед и только вперед!",
    description:
      "Я научился основе и начинаю делать свои пет проекты и формировать резюме",
    dkTranslateX: -608.912,
    tbTranslateX: -456.775,
    mbTranslateX: -426.047,
  },
  {
    mounth: "Январь",
    year: "2023",
    photo: "/dates/slide-7.jpg",
    title: "Первая работа",
    description: "Прохожу собеседование и устраиваюсь в компанию GetGain",
    dkTranslateX: -763.533,
    tbTranslateX: -561.545,
    mbTranslateX: -526.042,
  },
  {
    mounth: "Июль",
    year: "2023",
    photo: "/dates/slide-8.jpg",
    title: "Возвращение",
    description:
      "Возвращаюсь с военных учебных сборов и устраиваюсь в ГБУ БДД на позицию frontend разработчика",
    dkTranslateX: -928.51,
    tbTranslateX: -661.434,
    mbTranslateX: -608.418,
  },
  {
    mounth: "",
    year: "2023...",
    photo: "/dates/slide-9.jpg",
    title: "Стремления",
    description:
      "Поступил в магистратуру на бюджет, в первую половину дня работаю, во вторую половину дня делаю свои проекты, например этот!",
    dkTranslateX: -1089.23,
    tbTranslateX: -765.363,
    mbTranslateX: -690.908,
  },
];
